stages:
  - build
  - generateAPK

variables:
  LANG: "en_US.UTF-8"

before_script:
  - gem install bundler --user-install
  - bundle install

build:
  dependencies: []
  stage: buildRC
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  script:
    - bundle exec fastlane buildRC
  tags:
    - android

generateAPK:
  stage: generateAPK
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  script:
    - bundle exec fastlane generateDebugBuilds
  tags:
    - android