stages:
  - buildRC

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - export ANDROID_HOME="/sdk"
#  - gem install bundler
#  - bundle install

buildRC:
  dependencies: []
  stage: buildRC
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  script:
    - sudo chown -R ../builds/7H5m5hwt/0/muralikrishna.gs/GitLabCICD/scripts/*
    - fastlane buildRC
  tags:
    - android