stages:
  - buildRC

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - gem update --system
  - gem install bundler --user-install
  - bundle install

buildRC:
  dependencies: []
  stage: buildRC
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  script:
    - fastlane buildRC
  tags:
    - android