stages:
  - buildRC
  - generateAPK
  - generateSignedAPK
  - pushAppCenter

variables:
  LANG: "en_US.UTF-8"

before_script:
  - source ~/.bashrc
  - gem install bundler --user-install
  - bundle install
  - echo -e "STORE_PASSWORD=$STORE_PASSWORD\nKEY_ALIAS=$KEY_ALIAS\nKEY_PASSWORD=$KEY_PASSWORD" > app/signing.properties

build:
  dependencies: []
  stage: buildRC
  script:
    - bundle exec fastlane buildRC
  tags:
    - android

assembleDebug:
  stage: generateAPK
  script:
    - bundle exec fastlane generateDebugBuilds
  tags:
    - android

assembleRelease:
  stage: generateSignedAPK
  script:
    - bundle exec fastlane generateReleaseBuilds
  tags:
    - android

pushToAppCenter:
  stage: pushAppCenter
  script:
    - bundle exec fastlane appCenterInternal
  tags:
    - android