stages:
  - buildRC
  - generateAPK
  - generateSignedAPK

variables:
  LANG: "en_US.UTF-8"

before_script:
  - source ~/.bashrc
  - gem install bundler --user-install
  - bundle install

build:
  dependencies: []
  stage: buildRC
  before_script: echo "STORE_PASSWORD='$storePassword' KEY_ALIAS='$keyAlias' KEY_PASSWORD='$keyPassword'" > app/signing.properties
  script:
    - bundle exec fastlane buildRC
  tags:
    - android

assembleDebug:
  stage: generateAPK
  script:
    - bundle exec fastlane generateDebugBuilds
  tags:
    - android

assembleRelease:
  stage: generateSignedAPK
  script:
    - bundle exec fastlane generateReleaseBuilds
  tags:
    - android